# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal }:

cabal.mkDerivation (self: {
  pname = "picosat";
  version = "0.1.1";
  sha256 = "dfb58b78005aa2b550e2cec4f63eace1db084ed1ffac9cfd09897a4abc4713a3";
  meta = {
    homepage = "https://github.com/sdiehl/haskell-picosat";
    description = "Bindings to the PicoSAT solver";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
