# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal }:

cabal.mkDerivation (self: {
  pname = "picosat";
  version = "0.1.1";
  sha256 = "6f67a607da3d6144d38ee6454c67beda5aaab3ec0b91b277a60edb48e1728374";
  meta = {
    homepage = "https://github.com/sdiehl/haskell-picosat";
    description = "Bindings to the PicoSAT solver";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
